# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main Workflow

on: [push, pull_request]

jobs:
  # Run codestyle checks
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Linters
        run: npm run lint

  # Run tests
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Tests
        run: npm test

  # Build and deploy to Github Pages
  build_deploy:
    name: Build & Deploy

    runs-on: ubuntu-latest

    needs: [lint, test]

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run storybook:build

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploys
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          allow_empty_commit: true
